/**
 * Component Metadata Index
 * Auto-generated by scripts/collect-metadata.mjs
 * DO NOT EDIT MANUALLY
 */

import type { ComponentMetadata } from './types/metadata.js';

import { metadata as accordionMetadata } from './components/accordion/metadata.js';
import { metadata as alertMetadata } from './components/alert/metadata.js';
import { metadata as avatarMetadata } from './components/avatar/metadata.js';
import { metadata as badgeMetadata } from './components/badge/metadata.js';
import { metadata as breadcrumbMetadata } from './components/breadcrumb/metadata.js';
import { metadata as buttonMetadata } from './components/button/metadata.js';
import { metadata as cardMetadata } from './components/card/metadata.js';
import { metadata as checkboxMetadata } from './components/checkbox/metadata.js';
import { metadata as chipMetadata } from './components/chip/metadata.js';
import { metadata as colorPickerMetadata } from './components/color-picker/metadata.js';
import { metadata as containerMetadata } from './components/container/metadata.js';
import { metadata as datagridMetadata } from './components/datagrid/metadata.js';
import { metadata as datePickerMetadata } from './components/date-picker/metadata.js';
import { metadata as drawerMetadata } from './components/drawer/metadata.js';
import { metadata as fileUploadMetadata } from './components/file-upload/metadata.js';
import { metadata as formGroupMetadata } from './components/form-group/metadata.js';
import { metadata as gridMetadata } from './components/grid/metadata.js';
import { metadata as inputMetadata } from './components/input/metadata.js';
import { metadata as listMetadata } from './components/list/metadata.js';
import { metadata as menuMetadata } from './components/menu/metadata.js';
import { metadata as modalMetadata } from './components/modal/metadata.js';
import { metadata as paginationMetadata } from './components/pagination/metadata.js';
import { metadata as progressMetadata } from './components/progress/metadata.js';
import { metadata as radioMetadata } from './components/radio/metadata.js';
import { metadata as selectMetadata } from './components/select/metadata.js';
import { metadata as skeletonMetadata } from './components/skeleton/metadata.js';
import { metadata as sliderMetadata } from './components/slider/metadata.js';
import { metadata as spinnerMetadata } from './components/spinner/metadata.js';
import { metadata as stackMetadata } from './components/stack/metadata.js';
import { metadata as switchMetadata } from './components/switch/metadata.js';
import { metadata as tableMetadata } from './components/table/metadata.js';
import { metadata as tabsMetadata } from './components/tabs/metadata.js';
import { metadata as textareaMetadata } from './components/textarea/metadata.js';
import { metadata as themeSwitcherMetadata } from './components/theme-switcher/metadata.js';
import { metadata as timePickerMetadata } from './components/time-picker/metadata.js';
import { metadata as toastMetadata } from './components/toast/metadata.js';
import { metadata as tooltipMetadata } from './components/tooltip/metadata.js';

export const ALL_COMPONENT_METADATA: ComponentMetadata[] = [
  accordionMetadata,
  alertMetadata,
  avatarMetadata,
  badgeMetadata,
  breadcrumbMetadata,
  buttonMetadata,
  cardMetadata,
  checkboxMetadata,
  chipMetadata,
  colorPickerMetadata,
  containerMetadata,
  datagridMetadata,
  datePickerMetadata,
  drawerMetadata,
  fileUploadMetadata,
  formGroupMetadata,
  gridMetadata,
  inputMetadata,
  listMetadata,
  menuMetadata,
  modalMetadata,
  paginationMetadata,
  progressMetadata,
  radioMetadata,
  selectMetadata,
  skeletonMetadata,
  sliderMetadata,
  spinnerMetadata,
  stackMetadata,
  switchMetadata,
  tableMetadata,
  tabsMetadata,
  textareaMetadata,
  themeSwitcherMetadata,
  timePickerMetadata,
  toastMetadata,
  tooltipMetadata,
];

export function findComponentMetadata(query: string): ComponentMetadata | undefined {
  const lowerQuery = query.toLowerCase();
  return ALL_COMPONENT_METADATA.find(
    (c) =>
      c.name.toLowerCase() === lowerQuery ||
      c.tagName.toLowerCase() === lowerQuery ||
      c.description.toLowerCase().includes(lowerQuery)
  );
}

export function searchComponentMetadata(query: string): ComponentMetadata[] {
  const lowerQuery = query.toLowerCase();
  return ALL_COMPONENT_METADATA.filter(
    (c) =>
      c.name.toLowerCase().includes(lowerQuery) ||
      c.tagName.toLowerCase().includes(lowerQuery) ||
      c.description.toLowerCase().includes(lowerQuery) ||
      c.category.toLowerCase().includes(lowerQuery)
  );
}

export function getComponentMetadataByCategory(category: string): ComponentMetadata[] {
  return ALL_COMPONENT_METADATA.filter((c) => c.category === category);
}
