/**
 * Component Metadata Index
 * Auto-generated by scripts/collect-metadata.mjs
 * DO NOT EDIT MANUALLY
 */

import type { ComponentMetadata } from './types/metadata.js';

import { metadata as buttonMetadata } from './components/button/metadata.js';
import { metadata as cardMetadata } from './components/card/metadata.js';
import { metadata as inputMetadata } from './components/input/metadata.js';

export const ALL_COMPONENT_METADATA: ComponentMetadata[] = [
  buttonMetadata,
  cardMetadata,
  inputMetadata,
];

export function findComponentMetadata(query: string): ComponentMetadata | undefined {
  const lowerQuery = query.toLowerCase();
  return ALL_COMPONENT_METADATA.find(
    (c) =>
      c.name.toLowerCase() === lowerQuery ||
      c.tagName.toLowerCase() === lowerQuery ||
      c.description.toLowerCase().includes(lowerQuery)
  );
}

export function searchComponentMetadata(query: string): ComponentMetadata[] {
  const lowerQuery = query.toLowerCase();
  return ALL_COMPONENT_METADATA.filter(
    (c) =>
      c.name.toLowerCase().includes(lowerQuery) ||
      c.tagName.toLowerCase().includes(lowerQuery) ||
      c.description.toLowerCase().includes(lowerQuery) ||
      c.category.toLowerCase().includes(lowerQuery)
  );
}

export function getComponentMetadataByCategory(category: string): ComponentMetadata[] {
  return ALL_COMPONENT_METADATA.filter((c) => c.category === category);
}
